### ISSUE TITLE
Script closes / crash `invited you to play`

### ISSUE THREAD

**Issue by Suspectxyzz** [3urobeat/steam-idler#27]
Hi when I receive an invitation to the game, the script closes /crash
```
/home/cs2/src/bot.js:171
        const username  = this.user.users[steamID64] ? this.user.users[steamID64].player_name : ""; // Set username to nothing in case they are not cached yet to avoid errors
                                    ^

TypeError: Cannot read properties of undefined (reading 'users')
    at SteamChatRoomClient.<anonymous> (/home/cs2/src/bot.js:171:37)
    at SteamChatRoomClient.emit (node:events:517:28)
    at SteamUser.<anonymous> (/home/cs2/node_modules/steam-user/components/chatroom.js:1103:12)
    at /home/cs2/node_modules/steam-user/components/classes/HandlerManager.js:35:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (/home/cs2/node_modules/steam-user/components/classes/HandlerManager.js:34:12)
    at SteamUser._handleMessage (/home/cs2/node_modules/steam-user/components/03-messages.js:645:25)
    at SteamUser._handleNetMessage (/home/cs2/node_modules/steam-user/components/03-messages.js:565:8)
    at SteamUser._processMulti (/home/cs2/node_modules/steam-user/components/03-messages.js:697:9)

Node.js v18.19.1

```
v1.10
ubuntu server x64

**Comment by 3urobeat** [comment]
Hey, thanks for opening an issue.  
Seems like I have made a stupid copy & paste mistake when fixing a bug in the last update.  
I have pushed a fix, you can just pull changes/re-download again.
